type: object
required:
  - nombre
  - unidad_medida
  - idRestaurante # Changed from id_restaurante
properties:
  nombre:
    type: string
    maxLength: 255
    example: "Tomate Cherry"
  descripcion:
    type: string
    nullable: true
    example: "Tomates cherry para ensaladas y guarniciones."
  unidad_medida: # Ensure this matches model's 'field' if different
    type: string
    maxLength: 50
    example: "Kg"
  precio_compra: # Ensure this matches model's 'field' if different
    type: number
    format: float # DECIMAL(10,2) in model
    nullable: true
    minimum: 0
    example: 2.50
  stock_minimo: # Ensure this matches model's 'field' if different
    type: integer
    nullable: true
    minimum: 0
    example: 10
  idRestaurante: # Changed from id_restaurante
    type: integer
    example: 1
  idUsuario: # Added as optional, could be set by backend from auth user
    type: integer
    nullable: true
    description: "ID del usuario que registra el producto. Generalmente se establece automáticamente desde el token de autenticación."
    example: 123
